### ISSUE TITLE
line breaker

### ISSUE THREAD

**Issue by mfyang** [seomoz/dragnet#22]
Is it possible to keep line breaker in the extracted content?

**Comment by matt-peters** [comment]
I'm not sure what you mean by "line breaker"?  You can get the individual blocks with their text but all text in each block is whitespace normalized.

**Comment by mfyang** [comment]
ah. I see.  Yes, blocks are exactly what I meant.   How about title of the article then?

**Comment by matt-peters** [comment]
Yes you can get both the blocks and the title.  The `analyze` method on the trained models can optionally return the block objects instead of just text.  You can also provide a callback that is called on the lxml etree object.

Here's an example:

```python
import requests
from lxml.etree import XPath
from dragnet.models import content_extractor

title_xpath = XPath('//head/title')

title = {}
def callback(tree):
    title['title'] = '\n'.join(ele.text for ele in title_xpath(tree))

r = requests.get('https://moz.com/devblog/benchmarking-python-content-extraction-algorithms-dragnet-readability-goose-and-eatiht/')

blocks = content_extractor.analyze(r.content, blocks=True, 
    parse_callback=callback)
    
print(title['title'])
print('\n'.join([block.text for block in blocks]))
```

**Comment by mfyang** [comment]
Matt, this is great.  Thanks!

Another question, is it possible to keep the underlying links of the extracted texts? (Some texts may associated with links. Say   "<a href='xxx> link </a> is a good thing", now "link is a good thing" is extracted, but link is removed.  )

**Comment by matt-peters** [comment]
Absolutely.  You can get the links via a callback or as an attribute on the block object: `block.anchors` is a list of every `<a href=...` tag in the block (as `lxml.etree.Element` objects).
