### ISSUE TITLE
Installing error within WinPython

### ISSUE THREAD

**Issue by 0x54** [seomoz/dragnet#25]
Hi. I'm trying to install Dragnet but i got the following error. I have installed lxml, but it doesn't help. Any hint?

C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10>pip install dragnet
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Collecting dragnet
  Using cached dragnet-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\ti\appdata\local\temp\pip-build-3ujoqz\dragnet\setup.py", line 50, in <module>
        include_dirs = lxml.get_include() + [find_libxml2_include()],
      File "c:\users\ti\appdata\local\temp\pip-build-3ujoqz\dragnet\setup.py", line 36, in find_libxml2_include
        raise ValueError("Can't find libxml2 include headers")
    ValueError: Can't find libxml2 include headers

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in c:\users\ti\appdata\local\temp\pip-build-3ujoqz\dragnet

**Comment by b4hand** [comment]
lxml is not the same thing as libxml2. lxml is the python bindings for the libxml2. It's possible you used a precompiled installation of lxml on windows, but we need the actual header files for libxml2 to compile dragnet.

We don't currently use Windows or have any Windows machines to try out building dragnet, so you're pretty much on your own. If you don't have experience compiling software on Windows, you're going to have a hard time debugging things. Personally, I'd recommend using a linux virtual machine so that you can get an reasonable installation and not worry about running dragnet directly on Windows.

**Comment by matt-peters** [comment]
Can you try installing from the master branch? It has some minor bug fixes from the version on pip and we have removed the exception in your traceback.  If that doesn't work then as @b4hand said your best bet is to use a VM or debug it yourself.

**Comment by 0x54** [comment]
Thanks for replaying. I'm using Dragnet without any problem on Linux, but I'm interested in porting some code on Windows...
I've tryed installing from master without success:

C:\Users\ti\Downloads\dragnet-master>python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to dragnet.egg-info\requires.txt
writing dragnet.egg-info\PKG-INFO
writing top-level names to dragnet.egg-info\top_level.txt
writing dependency_links to dragnet.egg-info\dependency_links.txt
reading manifest file 'dragnet.egg-info\SOURCES.txt'
writing manifest file 'dragnet.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
skipping 'dragnet\_weninger.cpp' Cython extension (up-to-date)
skipping 'dragnet\lcs.cpp' Cython extension (up-to-date)
skipping 'dragnet\blocks.cpp' Cython extension (up-to-date)
building 'dragnet.blocks' extension
C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\Scripts\gcc.exe -mdll -O -Wall -IC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\lxml\includes -IC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\lxml -IC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python
-2.7.10\include -IC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\PC -c dragnet\blocks.cpp -o build\temp.win32-2.7\Release\dragnet\blocks.o
dragnet\blocks.cpp: In function 'void __Pyx_RaiseArgtupleInvalid(const char*, int, Py_ssize_t, Py_ssize_t, Py_ssize_t)':
dragnet\blocks.cpp:12173:59: warning: unknown conversion type character 'z' in format [-Wformat=]
                  (num_expected == 1) ? "" : "s", num_found);
                                                           ^
dragnet\blocks.cpp:12173:59: warning: format '%s' expects argument of type 'char*', but argument 5 has type 'Py_ssize_t {aka int}' [-Wformat=]
dragnet\blocks.cpp:12173:59: warning: unknown conversion type character 'z' in format [-Wformat=]
dragnet\blocks.cpp:12173:59: warning: too many arguments for format [-Wformat-extra-args]
dragnet\blocks.cpp: At global scope:
dragnet\blocks.cpp:1712:13: warning: 'void __pyx_f_7dragnet_6blocks_empty_callback(__pyx_obj_7dragnet_6blocks_PartialBlock*, std::string)' defined but not used [-Wunused-function]
 static void __pyx_f_7dragnet_6blocks_empty_callback(CYTHON_UNUSED struct __pyx_obj_7dragnet_6blocks_PartialBlock *__pyx_v_pb, CYTHON_UNUSED std::string __pyx_v_x) {
             ^
writing build\temp.win32-2.7\Release\dragnet\blocks.def
C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\Scripts\g++.exe -shared -s build\temp.win32-2.7\Release\dragnet\blocks.o build\temp.win32-2.7\Release\dragnet\blocks.def -LC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\libs -LC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\PCbuild -lxml
2 -lpython27 -lmsvcr90 -o build\lib.win32-2.7\dragnet\blocks.pyd
C:/Users/ti/Desktop/WinPython-32bit-2.7.10.2/python-2.7.10/share/mingwpy/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lxml2
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\Users\\ti\\Desktop\\WinPython-32bit-2.7.10.2\\python-2.7.10\\Scripts\\g++.exe' failed with exit status 1

Do you have any suggestion?

**Comment by matt-peters** [comment]
Looks like the compiler can't find the xml2 libraries during the linking step:

```
C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\Scripts\g++.exe -shared -s build\temp.win32-2.7\Release\dragnet\blocks.o build\temp.win32-2.7\Release\dragnet\blocks.def -LC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\libs -LC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\PCbuild -lxml
```

You should be able to fix this specifying the location of these libraries with `-L` similar to the how the python library locations are specified now.  On Linux-like OS you can do this with environmental variables, not sure about Windows.

**Comment by 0x54** [comment]
I've made a copy of the libxml2, named just xml2 but now I got another error :( :

C:\Users\ti\Downloads\dragnet-master>python   setup.py install
running install
running bdist_egg
running egg_info
writing requirements to dragnet.egg-info\requires.txt
writing dragnet.egg-info\PKG-INFO
writing top-level names to dragnet.egg-info\top_level.txt
writing dependency_links to dragnet.egg-info\dependency_links.txt
reading manifest file 'dragnet.egg-info\SOURCES.txt'
writing manifest file 'dragnet.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
skipping 'dragnet\_weninger.cpp' Cython extension (up-to-date)
skipping 'dragnet\lcs.cpp' Cython extension (up-to-date)
skipping 'dragnet\blocks.cpp' Cython extension (up-to-date)
skipping 'dragnet\readability.cpp' Cython extension (up-to-date)
building 'dragnet.readability' extension
C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\Scripts\gcc.exe -mdll -O -Wall -IC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\numpy\core\include -IC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\include -IC:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\PC
 -c dragnet\readability.cpp -o build\temp.win32-2.7\Release\dragnet\readability.o -std=c++0x
In file included from C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:1804:0,
                 from C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:17,
                 from C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\numpy\core\include/numpy/arrayobject.h:4,
                 from dragnet\readability.cpp:257:
C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h:13:79: note: #pragma message: C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated
NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
                          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION")
                                                                               ^
In file included from dragnet\readability.cpp:267:0:
dragnet\_readability.cc: In function 'void _readability_features(std::vector<unsigned int>&, std::vector<std::vector<std::pair<unsigned int, int> > >&, std::vector<std::vector<unsigned int> >&, std::vector<std::basic_string<char> >&, std::vector<double>&, int&, double*)':
dragnet\_readability.cc:32:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (std::size_t k = 0; k < nblocks; ++k)
                               ^
dragnet\_readability.cc:97:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (std::size_t k = 0; k < nblocks; ++k)
                               ^
In file included from C:/Users/ti/Desktop/WinPython-32bit-2.7.10.2/python-2.7.10/share/mingwpy/i686-w64-mingw32/include/c++/complex:44:0,
                 from dragnet\readability.cpp:466:
C:/Users/ti/Desktop/WinPython-32bit-2.7.10.2/python-2.7.10/share/mingwpy/i686-w64-mingw32/include/c++/cmath: At global scope:
C:/Users/ti/Desktop/WinPython-32bit-2.7.10.2/python-2.7.10/share/mingwpy/i686-w64-mingw32/include/c++/cmath:1094:11: error: '::hypot' has not been declared
   using ::hypot;
           ^
dragnet\readability.cpp: In function 'std::pair<unsigned int, int> __pyx_convert_pair_from_py_uint32_t__and_int(PyObject*)':
dragnet\readability.cpp:3958:74: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   __pyx_t_5 = __Pyx_PyInt_As_uint32_t(__pyx_v_x); if (unlikely(__pyx_t_5 == -1 && PyErr_Occurred())) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 165; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                          ^
dragnet\readability.cpp:439:43: note: in definition of macro 'unlikely'
   #define unlikely(x) __builtin_expect(!!(x), 0)
                                           ^
dragnet\readability.cpp: In function 'std::vector<unsigned int> __pyx_convert_vector_from_py_uint32_t(PyObject*)':
dragnet\readability.cpp:4184:79: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     __pyx_t_5 = __Pyx_PyInt_As_uint32_t(__pyx_v_item); if (unlikely(__pyx_t_5 == -1 && PyErr_Occurred())) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                               ^
dragnet\readability.cpp:439:43: note: in definition of macro 'unlikely'
   #define unlikely(x) __builtin_expect(!!(x), 0)
                                           ^
dragnet\readability.cpp: In function 'void __Pyx_RaiseArgtupleInvalid(const char*, int, Py_ssize_t, Py_ssize_t, Py_ssize_t)':
dragnet\readability.cpp:4875:59: warning: unknown conversion type character 'z' in format [-Wformat=]
                  (num_expected == 1) ? "" : "s", num_found);
                                                           ^
dragnet\readability.cpp:4875:59: warning: format '%s' expects argument of type 'char*', but argument 5 has type 'Py_ssize_t {aka int}' [-Wformat=]
dragnet\readability.cpp:4875:59: warning: unknown conversion type character 'z' in format [-Wformat=]
dragnet\readability.cpp:4875:59: warning: too many arguments for format [-Wformat-extra-args]
dragnet\readability.cpp: In function 'int __Pyx_BufFmt_ProcessTypeChunk(__Pyx_BufFmt_Context*)':
dragnet\readability.cpp:5210:78: warning: unknown conversion type character 'z' in format [-Wformat=]
                          ctx->head->field->type->arraysize[0], ctx->enc_count);
                                                                              ^
dragnet\readability.cpp:5210:78: warning: unknown conversion type character 'z' in format [-Wformat=]
dragnet\readability.cpp:5210:78: warning: too many arguments for format [-Wformat-extra-args]
dragnet\readability.cpp:5262:67: warning: unknown conversion type character 'z' in format [-Wformat=]
                    (Py_ssize_t)ctx->fmt_offset, (Py_ssize_t)offset);
                                                                   ^
dragnet\readability.cpp:5262:67: warning: unknown conversion type character 'z' in format [-Wformat=]
dragnet\readability.cpp:5262:67: warning: too many arguments for format [-Wformat-extra-args]
dragnet\readability.cpp: In function 'PyObject* __pyx_buffmt_parse_array(__Pyx_BufFmt_Context*, const char**)':
dragnet\readability.cpp:5324:69: warning: unknown conversion type character 'z' in format [-Wformat=]
                         ctx->head->field->type->arraysize[i], number);
                                                                     ^
dragnet\readability.cpp:5324:69: warning: too many arguments for format [-Wformat-extra-args]
dragnet\readability.cpp: In function 'int __Pyx_GetBufferAndValidate(Py_buffer*, PyObject*, __Pyx_TypeInfo*, int, int, int, __Pyx_BufFmt_StackElem*)':
dragnet\readability.cpp:5509:73: warning: unknown conversion type character 'z' in format [-Wformat=]
       dtype->name, (Py_ssize_t)dtype->size, (dtype->size > 1) ? "s" : "");
                                                                         ^
dragnet\readability.cpp:5509:73: warning: format '%s' expects argument of type 'char*', but argument 3 has type 'Py_ssize_t {aka int}' [-Wformat=]
dragnet\readability.cpp:5509:73: warning: unknown conversion type character 'z' in format [-Wformat=]
dragnet\readability.cpp:5509:73: warning: too many arguments for format [-Wformat-extra-args]
dragnet\readability.cpp: In function 'void __Pyx_RaiseTooManyValuesError(Py_ssize_t)':
dragnet\readability.cpp:5722:94: warning: unknown conversion type character 'z' in format [-Wformat=]
                  "too many values to unpack (expected %" CYTHON_FORMAT_SSIZE_T "d)", expected);
                                                                                              ^
dragnet\readability.cpp:5722:94: warning: too many arguments for format [-Wformat-extra-args]
dragnet\readability.cpp: In function 'void __Pyx_RaiseNeedMoreValuesError(Py_ssize_t)':
dragnet\readability.cpp:5728:48: warning: unknown conversion type character 'z' in format [-Wformat=]
                  index, (index == 1) ? "" : "s");
                                                ^
dragnet\readability.cpp:5728:48: warning: format '%s' expects argument of type 'char*', but argument 3 has type 'Py_ssize_t {aka int}' [-Wformat=]
dragnet\readability.cpp:5728:48: warning: too many arguments for format [-Wformat-extra-args]
In file included from C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\numpy\core\include/numpy/ufuncobject.h:317:0,
                 from dragnet\readability.cpp:258:
C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\numpy\core\include/numpy/__ufunc_api.h: At global scope:
C:\Users\ti\Desktop\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\numpy\core\include/numpy/__ufunc_api.h:241:1: warning: 'int _import_umath()' defined but not used [-Wunused-function]
 _import_umath(void)
 ^
error: command 'C:\\Users\\ti\\Desktop\\WinPython-32bit-2.7.10.2\\python-2.7.10\\Scripts\\gcc.exe' failed with exit status 1

**Comment by matt-peters** [comment]
This is your error:

```
C:/Users/ti/Desktop/WinPython-32bit-2.7.10.2/python-2.7.10/share/mingwpy/i686-w64-mingw32/include/c++/cmath:1094:11: error: '::hypot' has not been declared
```
Maybe you need the proper `-I` directory for `cmath.h`?

**Comment by b4hand** [comment]
Closing since we have no intention of supporting Windows builds. If someone would like to do the porting and maintain the port in a way that doesn't break the existing tests, we're not opposed to it, but this is not a priority.
