### ISSUE TITLE
Training content extraction models?

### ISSUE THREAD

**Issue by mtjoseph** [seomoz/dragnet#27]
After following the steps in the Training content extraction section, I'm getting a AttributeError on 'model.fit' when running the code to train additional/new content. What class needs to be instantiated for the model?

>>> from dragnet import models
>>> model = models.kohlschuetter_weninger_model
>>> dragnet.model_training.train_models(datadir, output_dir, features_to_use, model, 'both')
Reading the training and test data...
..done!
Got 980 training, 416 test documents
Initializing features
Training the model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/opt/virtualenvs/Dragnet/lib/python2.7/site-packages/dragnet/model_training.py", line 394, in train_models
    model.fit(features, labels, np.minimum(weights, 200.0))
AttributeError: 'ContentExtractionModel' object has no attribute 'fit'
>>>

Thanks!

**Comment by matt-peters** [comment]
Hello!  The model class needs have the sklearn interface and implement `.fit`.

We have two model abstractions in the code, one for a content extraction model (html -> content) and one for just the machine learning block model (sklearn classifier interface).  This function just trains the block model.  In our case, the trained versions distributed in dragnet now just use sklearn classes.

**Comment by mtjoseph** [comment]
I checked the sklearn docs and don't see any details concerning the 
actual implementation requirements for fit method. Can you provide a 
pointer to any docs or better an example implementation?

Thx

**Comment by matt-peters** [comment]
You could look at `LogisticRegression.fit` for instance:

http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.fit

**Comment by mtjoseph** [comment]
Perfect.

Thanks!
