### ISSUE TITLE
Error while training system

### ISSUE THREAD

**Issue by erolrecep** [seomoz/dragnet#30]
I got "MemoryError" while training system. 
<img width="634" alt="screen shot 2016-07-22 at 10 24 27 am" src="https://cloud.githubusercontent.com/assets/4239092/17061962/9106bf8e-4ff6-11e6-8714-4f1c42a8ca6a.png">
 
The output of the error is attached above.

What can be the reason to get this error? Also I changed memory amount of vagrant file from "1024" to "2048".

**Comment by matt-peters** [comment]
You probably need more memory then 2048 MB.  It's been some time since I've run the training so don't remember how much off hand -- but give your vagrant VM as much memory as you can and try again.

**Comment by erolrecep** [comment]
I think the problem is not the memory only. While I was trying to install pylab, after finishing matplotlib installation, the same error was appeared. The problem might be storage or version inconsistency.

**Comment by matt-peters** [comment]
This is almost certainly due to not enough memory in your vagrant VM.  Did you try to increase the memory and re-run?  I just now verified that `extract_gold_standard_all_training_data(rootdir)` runs without problems on a fresh Vagrant VM with 8192 MB of memory.
