### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zcs-seu** [seomoz/dragnet#31]
ubuntu 14.04;
error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dragnet/**init**.py", line 11, in <module>
    from .models import content_extractor, content_comments_extractor
  File "dragnet/models.py", line 21, in <module>
    content_extractor = pickle.load(fin)
  File "_tree.pyx", line 2217, in sklearn.tree._tree.Tree.__cinit__ (sklearn/tree/_tree.c:17574)
ValueError: ("Buffer dtype mismatch, expected 'SIZE_t' but got 'long long'", <type 'sklearn.tree._tree.Tree'>, (8, array([2], dtype=int64), 1))

Can you expain the reasons for the problem?
Thank you in advance!

**Comment by matt-peters** [comment]
What version of sklearn do you have?  Not sure what it is exactly but it could be a version mismatch between the pickled sklearn classifier in dragnet and the installed version.

**Comment by zcs-seu** [comment]
The working environment is set up according to your article. I redo it with the infomation below:
Requirement already satisfied (use --upgrade to upgrade): nose in /usr/local/lib/python2.7/dist-packages/nose-1.3.7-py2.7.egg (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): coverage in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.21.1 in /usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-i686.egg (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): scikit-learn<=0.16.1,>=0.15.2 in /usr/local/lib/python2.7/dist-packages/scikit_learn-0.15.2-py2.7-linux-i686.egg (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): mozsci in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): simplejson in /usr/lib/python2.7/dist-packages (from mozsci->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from mozsci->-r requirements.txt (line 8))

**Comment by matt-peters** [comment]
Well then I'm not sure what the issue is.  Can you provide some more details about how to reproduce the error?  Are you using the vagrant install or installing dependencies yourself?

I just confirmed that the tests pass in a fresh vagrant VM so I can't reproduce on my end.

**Comment by matt-peters** [comment]
Closed due to non-reproducibility.
