### ISSUE TITLE
Issue with detecting content

### ISSUE THREAD

**Issue by bowlesbe** [seomoz/dragnet#32]
One block was called 'Better Social Integration for Ultimate UX', and another was called 'Better Social Integration for Ultimate UX'. Yet, it thought there was content in the second, but not the first, why?

R324

0   0.000000  0.0          Better Social Integration for Ultimate UX  
1   0.000000  0.0                     Outspoken Media About Services  
2   0.000000  0.0  Link Development Online Reputation Management ...  
3   1.000000  0.0          Better Social Integration for Ultimate UX         Better Social Integration for Ultimate UX

**Comment by matt-peters** [comment]
The machine learning models in Dragnet use a few different types of features and not just the text in the block.  They also use information about the percent of text that is anchor text in the current, previous and next blocks as well as properties of the DOM subtree containing the block.  All this is to say that the classification for each segment isn't a local decision, it depends on some combination of the block, local context and entire document (and the block's location within the document).  As a result, the same bit of text or markup may have a different classification decision at different locations on the page.
