### ISSUE TITLE
error when installing on windows

### ISSUE THREAD

**Issue by gvola** [seomoz/dragnet#42]
Hello,
I'm new to python.
I cannot install Dragnet on Windows 7 due to an error with mozsci !
Any help possible ? Thanks

_Installing collected packages: scikit-learn, mozsci
  Found existing installation: scikit-learn 0.18.1
    Uninstalling scikit-learn-0.18.1:
      Successfully uninstalled scikit-learn-0.18.1
  **Running setup.py install for mozsci ... error**
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\vola-g~1.sav\\appdata\\local\\temp\\pip-build-q1
ppjo\\mozsci\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read(
).replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install
 --record c:\users\vola-g~1.sav\appdata\local\temp\pip-qdnl_z-record\install-rec
ord.txt --single-version-externally-managed --compile:_

**Comment by b4hand** [comment]
Sorry, but we don't have any Windows machines available to build on, so we can't provide compilation or installation help on Windows.

**Comment by b4hand** [comment]
Duplicates #25.
