### ISSUE TITLE
Error compiling Cython file

### ISSUE THREAD

**Issue by gvola** [seomoz/dragnet#45]
I have an error for > sudo make install

pair.from_py:152:13: 'uint32_t' is not a type identifier

**Comment by b4hand** [comment]
`uint32_t` is a standard type. See for example http://en.cppreference.com/w/cpp/types/integer. It is part of C and C++. This typically means you don't have the proper include headers installed on your system.

Without more information about which system you are trying to compile on and how you got there, it's impossible for anyone to help you.

The recommended development environment is the Vagrant-built image. If you use that, it is known to work. Anything else, and you're pretty much on your own to debug any compilation issues.
