### ISSUE TITLE
Can not use the latest version of sklearn

### ISSUE THREAD

**Issue by mahaoyang** [seomoz/dragnet#54]
python3.6/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator ExtraTreeClassifier from version 0.18.1 when using version 0.18.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

python3.6/site-packages/dragnet/models.py:51: UserWarning: Unable to unpickle ContentExtractionModel! Your version of scikit-learn (0.18.2) may not be compatible. Setting extractors to None.
  UserWarning)

**Comment by nehalecky** [comment]
hey @mahaoyang, this issue will be resolved when #52 is merged. We're trying to see that this happens soon!

**Comment by pakelley** [comment]
It looks like `sklearn`>=0.18 will complain when loading a model about any difference in the installed version of `sklearn` and the one used to train a model. As far as I can tell, Any version after 0.18 can load the models just fine, despite the warning.

Would an explanation of this behavior in the README be enough to consider this resolved? If so, I'd be happy to add a section there on the warning. Or is there a better way of handling this?

**Comment by b4hand** [comment]
I'm going to assume this was fixed by #52.
