### ISSUE TITLE
Getting started code snippet is not working

### ISSUE THREAD

**Issue by ibrahimsharaf** [seomoz/dragnet#55]
Hi, I've successfully installed dragnet on Python 2 as mentioned in the README, but when I try to run the demo snippet I get this error:

```
Traceback (most recent call last):
  File "/home/ibrahimsharaf/workspace/content_detection/dragtest.py", line 2, in <module>
    from dragnet import content_extractor, content_comments_extractor
ImportError: cannot import name content_extractor
```

Any clues?

**Comment by pakelley** [comment]
Ah yeah, that's my bad. I can make a PR to update those docs asap, but for now you should be able to get started using one of:
```
from dragnet import extract_content
extracted_content = extract_content(html_str)
```
for only content(and no comments), or:
```
from dragnet import extract_content_and_comments
extracted_content = extract_content_and_comments(html_str)
```
for, as you might have guessed, content and comments.

Hope that helps!

**Comment by ibrahimsharaf** [comment]
Thanks @pakelley, that worked!

**Comment by b4hand** [comment]
Reopening until the README is actually fixed.
