### ISSUE TITLE
lxml test error on master

### ISSUE THREAD

**Issue by pakelley** [seomoz/dragnet#56]
I've been looking into the test that's [failing in travis](https://travis-ci.org/seomoz/dragnet/builds/339212413), which is in the `test_lxml_error` on line 51 in `test_kohlschuetter.py` where it asserts `self.assertRaises(etree.XMLSyntaxError, etree.fromstring, '', etree.HTMLParser(recover=True))`.

This test was passing before #52 was merged the other day, and I haven't been able to sort out why it's failing on master: when I diff the Python 3 travis outputs, the only differences I notice are Python 3.5.5 vs 3.5.4 and different minor versions of `certifi` and `sqlite`.

Also, looking into that code, it seems that the `recover=True` param in the `HTMLParser` is specifically supposed to keep the expected `XMLSyntaxError` from occurring, and taking it out gives the expected behavior.

I have two questions on this:
  1. What is the value of enforcing that this error is raised?
  2. Why is `recover=True` being passed in, and is it important to the expected behavior? i.e. is it good enough if the exception is still raised when that param isn't passed into the parser?

@matt-peters, in addition to your knowledge of the codebase, it looks like you wrote this test, and I was wondering if you especially had any insight on this?

**Comment by matt-peters** [comment]
My memory of this code is a little hazy so can't give a complete answer.  However, a few things to consider:

* The `recover=True` is used when parsing the HTML (https://github.com/seomoz/dragnet/blob/master/dragnet/blocks.pyx#L846) so I presumably included it in the test case for consistency.  In the wild, much of the HTML is malformed so this is important for robustness when parsing.
* IIRC, `lxml` would raise a number of different types of errors, so we trap them all on the next line, before re-raising `BlockifyError` (this makes it much easier to explicitly trap parsing errors downstream).
* I don't think it's important to keep that exact test in the code (if something in `lxml` or the environment now means that a different exception, or no exception is raised), as long as we include a test where `lxml` does raise an exception during parsing and it is handled properly.  Is there another test document other then `''` that will trigger an exception?

**Comment by matt-peters** [comment]
If you remove https://github.com/seomoz/dragnet/blob/master/test/test_kohlschuetter.py#L51 but keep https://github.com/seomoz/dragnet/blob/master/test/test_kohlschuetter.py#L52 does the test pass?  Since `lxml` doesn't return a valid parse for `""` then it's really only necessary to check that the appropriate exception is raised.

After some thought, this may be related to a change in the underlying `libxml2` library that `lxml` uses under the hood.

**Comment by pakelley** [comment]
Yep, taking that line out makes the test pass. I'm happy to open another PR with that change if that works for you

**Comment by matt-peters** [comment]
Works for me, thanks.
