### ISSUE TITLE
model file size is around 447Kb for new training using same dataset

### ISSUE THREAD

**Issue by Nitin-Panwar** [seomoz/dragnet#64]
I am trying to train same ExtraTreeClassifier using same dragnet_dataset, but i am getting very small sized model pickle file and prediction accuracy is also very poor as compare to the existing model. 
Original model file size - ~50MB
New model file size - 447KB

Am i doing any mistake in training? any help is appreciated.

**Comment by pakelley** [comment]
I figure this is related to the issue I was having in #63 with training new models. The pickled models that are in the current HEAD of the library were trained with a much larger random forest than previous versions, which makes the throughput much slower.

I changed the way the training happens a bit to improve performance of the models. Once I'm finished hammering out the details of those changes I'll submit them in that PR, and the performance of trained models should improve when that update gets merged. 🙂

**Comment by Nitin-Panwar** [comment]
Thanks for the reply. I will be waiting for the PR to be merged, also I would love to know which machine learning model are you using this time to get the good F1 score, Have you tried deep learning approaches to get the good accuracy.? Because as per my understanding existing models in dragnet are built years before using old ML techniques.

**Comment by b4hand** [comment]
I'm guessing this is resolved by #63, right?

**Comment by pakelley** [comment]
I think so, but would you mind verifying that @Nitin-Panwar when you have a chance? 

Also, if you're extracting your data manually the API for training is slightly different now: see the updated README in #65 for details if you need them.

If you're just using the `train_model` call to train, there will be no difference.
